[runner]
workers = 2
wmdrun = [ "not used", "not used"]

[simulation]
interfaces = [ -0.1, 0.0, 0.1]
steps = 200000
seed = 0
load_dir = "load"
shooting_moves = [ "sh", "sh", "sh"]

[simulation.tis_set]
maxlength = 100000
allowmaxlength = false
zero_momentum = false
n_jumps = 3
lambda_minus_one = -0.2

[engine]
class = "ase"
engine = "ase"
temperature = 11604.518121550082
input_path = "."
timestep = 0.020361011421549486 # check this, ase_engine uses fs units here
subcycles = 1
integrator = "langevin"
langevin_fixcm = false
langevin_friction = 1.96453895004769751864159843535162508487701416015625 # also here, units are 1/fs

[engine.calculator_settings]
module = "./flat_nowalls_ase.py"
class = "FlatWalls1D"
k = 0.0
left = -0.2
right = 0.4

[orderparameter]
class = "Position"
index = [ 0, 0, ]
periodic = false

[output]
data_dir = "./"
screen = 1
pattern = true
delete_old = true
delete_old_all = false
