[infinit]
cstep = 0
steps_per_iter = [20,]
lamres = 0.01
skip = 0.1

[runner]
workers = 1
wmdrun = [0]

[simulation]
interfaces = [-9.9, 10.0]
steps = 10
seed = 0
load_dir = 'load'
shooting_moves = ['sh','sh']

[simulation.tis_set]
maxlength = 50000
allowmaxlength = false
zero_momentum = false
n_jumps = 2

[engine]
class = 'ase_external'
input_path = 'openmm_input'
integrator = "external"
# results in kB*T = 0.07 kJ/mol
temperature = 8.419027001022311
# these are set in [engine.calculator_settings]
timestep = 0
subcycles = 0
# required since OpenMM stores half-step velocities for most built-in integrators
halfstep_vel = true
# We excplicitly set a small sleep time here because double-well runs fast
sleep = 0.05

[engine.calculator_settings]
module = "../openmmcalculator.py"
class = "OpenMMCalculator"
# there are some duplicate keywords at the moment
subcycles = 1
timestep_ps = 0.025
friction_per_ps = 0.3
temperature = 8.419065478920945
halfstep_vel = true

[orderparameter]
class = 'Position'
index = [ 0, 0]
periodic = false

[output]
data_dir = "./"
screen = 1
pattern = false
delete_old = true
keep_maxop_trajs = true
