[infinit]
pL = 0.3
initial_conf = "../right_well.traj"
lamres = 0.001
skip = 0.1
steps_per_iter = [
    30,
    30,
    30,
    30,
    30,
    30,
    30,
    30,
    30,
    30,
    30,
    30,
    30,
    30,
    30,
    30,
    30,
    30,
    30,
    30,
    30,
    30,
    30,
]
cstep = -1

[runner]
workers = 1
wmdrun = [ 1,1,1,1]

[simulation]
interfaces = [-0.9900, 1.0000]
steps = 1000
seed = 0
load_dir = "load"
shooting_moves = ["sh", "sh", "wf", "wf", "wf", "wf", "wf"]

[simulation.tis_set]
maxlength = 50000
allowmaxlength = false
zero_momentum = false
n_jumps = 3

[engine]
class = "ase"
engine = "ase"
temperature = 812.3165442280706 # 0.07/ase.units.kB
input_path = "."
timestep = 0.10180505671156725 # 0.01/ase.units.fs
subcycles = 1
integrator = "langevin"
langevin_fixcm = false
langevin_friction = 0.029468084365392187 # = 0.3*ase.units.fs

[engine.calculator_settings]
module = "../potential.py"
class = "Potential2D"
a = 1.3128
b = 2.0
c = 0.25

[orderparameter]
class = "OrderX"
module = "../orderx_r.py"
a = 1.3128
b = 2.0
c = 0.25

[output]
data_dir = "./"
screen = 1
pattern = false
delete_old = false
